export const MATCHER_ITEMS = [
  { id: "idli", name: "Idli", category: "Food", correctState: "Tamil Nadu" },
  { id: "dosa", name: "Dosa", category: "Food", correctState: "Tamil Nadu" },
  {
    id: "kathakali",
    name: "Kathakali",
    category: "Dance",
    correctState: "Kerala",
  },
  {
    id: "bharatanatyam",
    name: "Bharatanatyam",
    category: "Dance",
    correctState: "Tamil Nadu",
  },
  { id: "dhokla", name: "Dhokla", category: "Food", correctState: "Gujarat" },
  { id: "garba", name: "Garba", category: "Dance", correctState: "Gujarat" },
  { id: "lassi", name: "Lassi", category: "Food", correctState: "Punjab" },
  { id: "bhangra", name: "Bhangra", category: "Dance", correctState: "Punjab" },
  {
    id: "samosa",
    name: "Samosa",
    category: "Food",
    correctState: "Uttar Pradesh",
  },
  {
    id: "kathak",
    name: "Kathak",
    category: "Dance",
    correctState: "Uttar Pradesh",
  },
  {
    id: "biryani",
    name: "Biryani",
    category: "Food",
    correctState: "Telangana",
  },
  {
    id: "kuchipudi",
    name: "Kuchipudi",
    category: "Dance",
    correctState: "Andhra Pradesh",
  },
  {
    id: "rogan-josh",
    name: "Rogan Josh",
    category: "Food",
    correctState: "Kashmir",
  },
  { id: "appam", name: "Appam", category: "Food", correctState: "Kerala" },
  {
    id: "mohiniyattam",
    name: "Mohiniyattam",
    category: "Dance",
    correctState: "Kerala",
  },
  {
    id: "tandoori",
    name: "Tandoori Chicken",
    category: "Food",
    correctState: "Punjab",
  },
  { id: "odissi", name: "Odissi", category: "Dance", correctState: "Odisha" },
  { id: "pakhala", name: "Pakhala", category: "Food", correctState: "Odisha" },
  {
    id: "vada",
    name: "Medu Vada",
    category: "Food",
    correctState: "Tamil Nadu",
  },
  {
    id: "sattriya",
    name: "Sattriya",
    category: "Dance",
    correctState: "Assam",
  },
];

export const STATES = [
  "Tamil Nadu",
  "Kerala",
  "Gujarat",
  "Punjab",
  "Uttar Pradesh",
  "Telangana",
  "Andhra Pradesh",
  "Kashmir",
  "Odisha",
  "Assam",
];
